<a href="https://colab.research.google.com/github/eliasdengo/Python-practice-from-beginning-to-advance/blob/Eliasrepos/Diabetes_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


importing dependance

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

data collection and processsing

In [2]:
diabetes_data=pd.read_csv('/content/sample_data/diabetes.csv')

In [3]:
# top 5 data
diabetes_data.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [5]:
# tails of 5 data
diabetes_data.tail()

     Pregnancies  Glucose  ...  Age  Outcome
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[5 rows x 9 columns]

In [6]:
# diabetes data column and row
diabetes_data.shape

(768, 9)

In [7]:
# more information in diabetes data
diabetes_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [8]:
# it has misssing data
diabetes_data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
# statsticall information of diabetes data
diabetes_data.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [16]:
# distribution of diabete  or not
diabetes_data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [19]:
diabetes_data.groupby('Outcome').mean()

         Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

separate feature and target

standardization of data

In [21]:
x=diabetes_data.drop(columns='Outcome',axis=1)
y=diabetes_data['Outcome']

In [22]:
print(x)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [23]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [20]:
scaler=StandardScaler()

In [24]:
scaler.fit(x)

StandardScaler()

In [26]:
x=scaler.transform(x)

spliting data for training data and testing data

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [28]:
print(x.shape,x_train.shape,x_test.shape )

(768, 8) (614, 8) (154, 8)

train machine learning models

In [29]:
model=svm.SVC()

In [31]:
model.fit(x_train,y_train)

SVC()

Evaluation of trained models

In [36]:
# x train prediction
x_train_prediction=model.predict(x_train)

In [35]:
# x train accuracy
x_train_accuracy=accuracy_score(x_train_prediction,y_train)

In [37]:
print('accuracy score of training data',x_train_accuracy)

accuracy score of training data 0.8289902280130294

In [39]:
# x test prediction
x_test_prediction=model.predict(x_test)

In [40]:
# train accuracy
x_test_accuracy=accuracy_score(x_test_prediction,y_test)

In [41]:
print('accuracy score of testing data',x_test_accuracy)

accuracy score of testing data 0.7272727272727273

diabetes prediction system

In [43]:
input_data=(10,115,0,0,0,35.3,0.134,29)
input_data_as_array=np.asarray(input_data)
input_data_reshaped=input_data_as_array.reshape(1,-1)

std_data=scaler.transform(input_data_reshaped)
prediction=model.predict(std_data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [44]:
if prediction[0]==0:
  print('person is not diabetic')
else:
  print('person is diabetic')

person is not diabetic