<a href="https://colab.research.google.com/github/eliasdengo/Python-practice-from-beginning-to-advance/blob/Eliasrepos/Feature_Engineering_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.metrics import mean_squared_error

In [ ]:
df=pd.read_csv('/content/sample_data/housing.csv')

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [ ]:
df.dropna().sum()

longitude                                                   -2443187.88
latitude                                                      728093.61
housing_median_age                                             585060.0
total_rooms                                                  53871691.0
total_bedrooms                                               10990309.0
population                                                   29115941.0
households                                                   10204924.0
median_income                                                 79099.445
median_house_value                                         4226860554.0
ocean_proximity       NEAR BAYNEAR BAYNEAR BAYNEAR BAYNEAR BAYNEAR B...
dtype: object

In [ ]:
df.dropna()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

split test and train data

In [ ]:
df=df.sample(frac=0.8,random_state=2)
train_data=df[:17000]
train_data=train_data.reset_index(drop=True)
test_data=df[17000:]
test_data=test_data.reset_index(drop=True)

In [ ]:
train_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-117.65,33.60,15.0,5736.0,NaN,2529.0,762.0,6.4114,278700.0,<1H OCEAN
1,-120.91,38.62,12.0,4545.0,748.0,2033.0,718.0,4.1843,207600.0,INLAND
2,-118.23,33.93,35.0,1149.0,277.0,909.0,214.0,1.7411,96700.0,<1H OCEAN
3,-122.37,37.59,39.0,4645.0,1196.0,2156.0,1113.0,3.4412,353800.0,NEAR OCEAN
4,-117.98,33.70,16.0,5127.0,631.0,2142.0,596.0,7.8195,390500.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
16507,-117.67,34.04,13.0,1543.0,NaN,776.0,358.0,3.0598,99700.0,INLAND
16508,-117.44,33.88,5.0,2589.0,351.0,1109.0,360.0,6.8089,334100.0,INLAND
16509,-118.12,34.69,17.0,2479.0,390.0,1219.0,363.0,4.6417,125700.0,INLAND
16510,-121.68,39.29,29.0,1860.0,400.0,1137.0,365.0,1.5281,61600.0,INLAND
16511,-121.97,37.52,23.0,4925.0,948.0,2530.0,894.0,5.0824,230900.0,<1H OCEAN

In [ ]:
train_data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [ ]:
y_train=train_data['median_house_value'].to_numpy()
x_train=train_data['median_house_value'].to_numpy()

Get error of baseline model that uses the avarage median house value in train data

In [ ]:
avarage_median_house_value=train_data['median_house_value'].mean()

In [ ]:
baseline_model_test_prediction =[avarage_median_house_value]* len(y_train)

In [ ]:
mean_squared_error(baseline_model_test_prediction,x_train)

13352884045.781326

1.dimensional reduction (PCA)

In [ ]:
train_data[['households','total_rooms','total_bedrooms']].corr()

                households  total_rooms  total_bedrooms
households        1.000000     0.919761        0.980885
total_rooms       0.919761     1.000000        0.929910
total_bedrooms    0.980885     0.929910        1.000000

Get x_train_3

In [ ]:
x_train_3=train_data[['households','total_rooms','total_bedrooms']].to_numpy()

In [ ]:
x_train_3.shape

(16512, 3)

Get x_test_3

In [ ]:
x_test_3=test_data[['households','total_rooms','total_bedrooms']].to_numpy()

In [ ]:
x_test_3.shape

(0, 3)